apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
    containers:
    - name: hello-app
      image: gcr.io/thematic-land-251219/docker-go-service:latest
      ports:
      - containerPort: 8080
      env:
        - name: PORT
        value: "8080"
